package com.jsancue.kafka_cero_a_experto.user.infrastructure.api;

import com.jsancue.kafka_cero_a_experto.autogenerated.events.user.UserCreatedEvent;
import com.jsancue.kafka_cero_a_experto.common.infrastructure.event.producer.KafkaProducer;
import com.jsancue.kafka_cero_a_experto.user.domain.entity.User;
import com.jsancue.kafka_cero_a_experto.user.domain.port.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.Optional;

@RestController
@RequestMapping("/api/v1/users")
@RequiredArgsConstructor
public class UserController {
    private final KafkaProducer kafkaProducer;
    private final UserRepository userRepository;

    @GetMapping("/create")
    public void createUser(User user) {
        System.out.println("Creating user");
        UserCreatedEvent userCreatedEvent = UserCreatedEvent.newBuilder()
                .setId(1L)
                .setFirstname("Jesús")
                .setLastname("Sánchez")
                .setEmail("support@jsancue.com")
                .setRole("USER")
                .setTimestamp(System.currentTimeMillis())
                .build();

        kafkaProducer.send("user.events", userCreatedEvent);
    }

    @GetMapping("/{id}")
    public ResponseEntity<User> getUser(@PathVariable Long id) {
        Optional<User> user = userRepository.findById(id);

        return user.map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.notFound().build());
    }
}
