package com.jsancue.kafka_cero_a_experto.user.infrastructure.event.consumer.specific;

import com.jsancue.kafka_cero_a_experto.autogenerated.events.user.UserCreatedEvent;
import com.jsancue.kafka_cero_a_experto.common.application.Mediator;
import com.jsancue.kafka_cero_a_experto.common.infrastructure.event.consumer.EventSpecificConsumer;
import com.jsancue.kafka_cero_a_experto.user.application.created.UserCreatedCommand;
import com.jsancue.kafka_cero_a_experto.user.infrastructure.event.mapper.UserEventMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.messaging.Message;
import org.springframework.stereotype.Component;

@Component
@Slf4j
@RequiredArgsConstructor
public class UserCreatedSpecificConsumer implements EventSpecificConsumer<UserCreatedEvent> {

    private final Mediator mediator;
    private final UserEventMapper userEventMapper;

    @Override
    public void accept(Message<UserCreatedEvent> genericRecordMessage) {
        log.info("UserCreatedSpecificConsumer message: {}", genericRecordMessage.toString());
        UserCreatedCommand userCreatedCommand = userEventMapper.mapToUserCreatedCommand(genericRecordMessage.getPayload());

        mediator.dispatch(userCreatedCommand);
    }

    @Override
    public String getSchema() {
        return UserCreatedEvent.getClassSchema().getFullName();
    }
}
