package com.jsancue.kafka_cero_a_experto.user.infrastructure.event.mapper;

import com.jsancue.kafka_cero_a_experto.autogenerated.events.user.*;
import com.jsancue.kafka_cero_a_experto.common.infrastructure.event.util.MapperUtils;
import com.jsancue.kafka_cero_a_experto.user.application.created.UserCreatedCommand;
import com.jsancue.kafka_cero_a_experto.user.application.deleted.UserDeletedCommand;
import com.jsancue.kafka_cero_a_experto.user.application.emailUpdated.UserEmailUpdatedCommand;
import com.jsancue.kafka_cero_a_experto.user.domain.event.UserDeactivatedDomainEvent;
import com.jsancue.kafka_cero_a_experto.user.domain.event.UserVerificationRequestedDomainEvent;
import org.mapstruct.Mapper;
import org.mapstruct.ReportingPolicy;


@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface UserEventMapper extends MapperUtils {

    UserCreatedCommand mapToUserCreatedCommand(UserCreatedEvent event);

    UserEmailUpdatedCommand mapToUserEmailUpdatedCommand(UserEmailUpdatedEvent event);

    UserDeletedCommand mapToDeletedCommand(UserDeletedEvent event);

    UserDeactivatedEvent mapToUserDeactivatedEvent(UserDeactivatedDomainEvent event);

    UserVerificationRequestedEvent mapToUserVerificationRequestedEvent(UserVerificationRequestedDomainEvent event);

}
